FROM golang:1.23-bookworm as builder

ARG ACCESS_TOKEN

RUN git config --global url."https://x-access-token:${ACCESS_TOKEN}@github.com".insteadOf "https://github.com"

WORKDIR /app

COPY . .

RUN go build -o checker cmd/checker/*.go

FROM ubuntu:24.04

RUN apt update && apt install -y ca-certificates wget
RUN update-ca-certificates

WORKDIR /app

COPY --from=builder /app/checker /app

ENTRYPOINT ["/app/checker"]