version: '3.8'

services:
  consistency-checkerx:
    image: 294354037686.dkr.ecr.ap-northeast-1.amazonaws.com/consistency-checkerx:latest
    network_mode: "host"
    container_name: consistency-eth
    volumes:
      - /data/consistency-eth:/eth
      - ./config:/config
    command: ["-config", "/config/config.yml"]